version: "3.8"

services:

  rails:
    build: .
    # volumes:
    #   - .:/code:cached

    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

    ports:
      - "3000:3000"

    # Specify the values of the environment variables
    # used in this container.
    environment:
      RAILS_ENV: development
    #   DATABASE_NAME: boats_development
    #   DATABASE_USER: boats_development
    #   DATABASE_PASSWORD: 
    #   DATABASE_HOST: database

# Declare the volumes that our application uses.
# volumes:
#   db_data: